# add this file

version: '3.8'

services:

  couchdb:
    image: couchdb:${DB_COUCHDB_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    restart: always
    ports:
     - ${DB_COUCHDB_PORT}:5984
    volumes:
     - couchdb_data:/opt/couchdb/data
     - couchdb_etc:/opt/couchdb/etc/local.d
    # - couchdb/vm.args:/opt/couchdb/etc/vm.args #Changing these values is less common,to store Erlang runtime-specific changes
    environment:
      COUCHDB_USER: ${DB_COUCHDB_USER}
      COUCHDB_PASSWORD: ${DB_COUCHDB_PASSWORD}

networks:
  default:
      name: ${APP_NETWORK}

volumes:
  couchdb_data:
  couchdb_etc:
